### ISSUE TITLE
Why is the decryption key needed?

### ISSUE THREAD

**Issue by raomin** [ahpohl/xiaomi_lywsd03mmc#2]
I am wondering why this project need a decryption key for this sensor (and mitm ssl is not trivial) while other projects (eg https://github.com/polclota/esp32lywsd03mmc ) simply connects to the service and characteristic to read the values without the need for a decryption key.

**Comment by ahpohl** [comment]
> while other projects (eg https://github.com/polclota/esp32lywsd03mmc ) simply connects to the service and characteristic

The goal was to read the temperature and humidity values without an active bluetooth connection. The device broadcasts BLE packets every 10 min., but the payload inside the packets is encrypted. When you actively connect to the device, then the decryption happens on the fly.

**Comment by ahpohl** [comment]
The lywsd03mmc device is now fully supported by ESPHome and HomeAssistant, which both do not require and an active bluetooth connection saving battery power.

**Comment by raomin** [comment]
Understood. Makes sense. Thanks!

**Comment by raomin** [comment]
Rationale provided, thanks.
